/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as QueryBuilderImport } from './routes/query-builder';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const QueryBuilderRoute = QueryBuilderImport.update({
	id: '/query-builder',
	path: '/query-builder',
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/': {
			id: '/';
			path: '/';
			fullPath: '/';
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		'/query-builder': {
			id: '/query-builder';
			path: '/query-builder';
			fullPath: '/query-builder';
			preLoaderRoute: typeof QueryBuilderImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	'/': typeof IndexRoute;
	'/query-builder': typeof QueryBuilderRoute;
}

export interface FileRoutesByTo {
	'/': typeof IndexRoute;
	'/query-builder': typeof QueryBuilderRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	'/': typeof IndexRoute;
	'/query-builder': typeof QueryBuilderRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: '/' | '/query-builder';
	fileRoutesByTo: FileRoutesByTo;
	to: '/' | '/query-builder';
	id: '__root__' | '/' | '/query-builder';
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	QueryBuilderRoute: typeof QueryBuilderRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	QueryBuilderRoute: QueryBuilderRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/query-builder"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/query-builder": {
      "filePath": "query-builder.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
